# Generated by Django 3.0.5 on 2020-04-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(null=True)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=2000000)),
                ('image', models.TextField(max_length=1000)),
                ('publisher', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=200)),
                ('genre', models.TextField(max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('pages', models.IntegerField(null=True)),
                ('book', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=100)),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='api.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='api.Category'),
        ),
    ]
