# Generated by Django 3.0.5 on 2020-04-25 21:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(to='api.Book', verbose_name='list_of_books'),
        ),
    ]
