# Generated by Django 3.0.5 on 2020-04-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200425_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(null=True, to='api.Book', verbose_name='list_of_books'),
        ),
    ]
