# Generated by Django 3.0.5 on 2020-04-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200425_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(to='api.Book', verbose_name='list_of_books'),
        ),
    ]
