# Generated by Django 3.0.5 on 2020-04-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200425_2145'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.CreateModel(
            name='MyBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(to='api.Book')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.MyBooks'),
        ),
    ]
